# Generated by Django 6.0 on 2026-01-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_alter_employee_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="hr.team"
            ),
        ),
    ]
